# Generated by Django 5.0.14 on 2026-08-06 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True)),
                ('splitter', models.CharField(blank=True, max_length=20, null=True)),
                ('status_atual', models.CharField(choices=[('normal', 'Normal'), ('proxima_lotacao', 'Próxima da lotação'), ('lotada', 'Lotada'), ('danificada', 'Danificada')], default='normal', max_length=20)),
                ('portas_livres_atual', models.IntegerField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CTO',
                'verbose_name_plural': 'CTOs',
                'indexes': [models.Index(fields=['bairro'], name='ctos_cto_bairro_8ff96e_idx'), models.Index(fields=['status_atual'], name='ctos_cto_status__d64669_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('normal', 'Normal'), ('proxima_lotacao', 'Próxima da lotação'), ('lotada', 'Lotada'), ('danificada', 'Danificada')], max_length=20)),
                ('motivo', models.CharField(blank=True, choices=[('sem_porta_livre', 'Sem porta livre'), ('sem_splitter', 'Sem splitter'), ('porta_rompida', 'Porta rompida'), ('fibra_rompida', 'Fibra rompida'), ('caixa_quebrada', 'Caixa quebrada'), ('poste_interditado', 'Poste interditado'), ('sem_energia', 'Sem energia'), ('cto_inexistente', 'CTO inexistente'), ('cto_muito_distante', 'CTO muito distante'), ('outro', 'Outro')], max_length=30, null=True)),
                ('portas_usadas', models.IntegerField(blank=True, null=True)),
                ('portas_livres', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ocorrencias/%Y/%m/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('latitude_registro', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude_registro', models.DecimalField(decimal_places=7, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ctos.cto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cto', '-criado_em'], name='ctos_ocorre_cto_id_29c76c_idx'), models.Index(fields=['situacao'], name='ctos_ocorre_situaca_5a071b_idx')],
            },
        ),
    ]
