# Generated by Django 5.2.17 on 2026-08-07 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocorrencia',
            index=models.Index(fields=['criado_em'], name='ctos_ocorre_criado__ae69e0_idx'),
        ),
    ]
