# Generated by Django 5.2.17 on 2026-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctos', '0002_ocorrencia_ctos_ocorre_criado__ae69e0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cto',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
