# Generated by Django 5.2.17 on 2026-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctos', '0003_cto_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cto',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
